// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {platform} from '../models';
import {downloader} from '../models';
import {main} from '../models';

export function AddBookmark(arg1:string,arg2:string):Promise<config.FolderBookmark>;

export function CancelItem(arg1:string):Promise<void>;

export function CheckDiskSpace(arg1:string):Promise<platform.DiskSpaceInfo>;

export function DeleteBookmark(arg1:string):Promise<void>;

export function GetBookmarks():Promise<Array<config.FolderBookmark>>;

export function GetQueueItems():Promise<Array<downloader.DownloadItem>>;

export function GetSettings():Promise<config.Settings>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenHFTokenPage():Promise<void>;

export function ParseAndInspect(arg1:string):Promise<main.InspectResponse>;

export function PauseItem(arg1:string):Promise<void>;

export function QueueItems(arg1:Array<downloader.DownloadItem>,arg2:boolean):Promise<Array<downloader.DownloadItem>>;

export function RemoveItem(arg1:string):Promise<void>;

export function ResumeItem(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SelectDirectoryDialog(arg1:string):Promise<string>;

export function StartItem(arg1:string):Promise<void>;

export function UpdateItemDestination(arg1:string,arg2:string):Promise<void>;

export function VerifyLocalFile(arg1:downloader.DownloadItem):Promise<downloader.VerificationResult>;
