// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2);
}

export function CancelItem(arg1) {
  return window['go']['main']['App']['CancelItem'](arg1);
}

export function DeleteBookmark(arg1) {
  return window['go']['main']['App']['DeleteBookmark'](arg1);
}

export function GetBookmarks() {
  return window['go']['main']['App']['GetBookmarks']();
}

export function GetQueueItems() {
  return window['go']['main']['App']['GetQueueItems']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenHFTokenPage() {
  return window['go']['main']['App']['OpenHFTokenPage']();
}

export function ParseAndInspect(arg1) {
  return window['go']['main']['App']['ParseAndInspect'](arg1);
}

export function PauseItem(arg1) {
  return window['go']['main']['App']['PauseItem'](arg1);
}

export function QueueItems(arg1, arg2) {
  return window['go']['main']['App']['QueueItems'](arg1, arg2);
}

export function RemoveItem(arg1) {
  return window['go']['main']['App']['RemoveItem'](arg1);
}

export function ResumeItem(arg1) {
  return window['go']['main']['App']['ResumeItem'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectoryDialog(arg1) {
  return window['go']['main']['App']['SelectDirectoryDialog'](arg1);
}

export function StartItem(arg1) {
  return window['go']['main']['App']['StartItem'](arg1);
}

export function UpdateItemDestination(arg1, arg2) {
  return window['go']['main']['App']['UpdateItemDestination'](arg1, arg2);
}

export function VerifyLocalFile(arg1) {
  return window['go']['main']['App']['VerifyLocalFile'](arg1);
}
